cache:
  untracked: true
  paths:
    - vendor/ruby
    - node_modules

variables:
  RAILS_ENV: test
  RAILS_GROUPS: build
  POSTGRES_DB: nice_marmot

linter:
  image: atomicjolt/atomicjolt-ci:ruby-2.5.7--node-10.18.0--yarn-1.10.1
  only:
    - merge_requests
  except:
    - master
  before_script:
    - yarn
    - bundle install --path vendor
    - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
  script:
    - PRONTO_GITLAB_API_ENDPOINT=https://gitlab.com/api/v4/ bundle exec pronto run -r eslint rubocop -f gitlab_mr -c origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --exit-code


rspec:
  image: atomicjolt/atomicjolt-ci:ruby-2.5.7--node-10.18.0--yarn-1.10.1
  only:
    - master
    - /.*\..*/
    - merge_requests
  services:
    - postgres:9.5.0
  before_script:
    - cp config/secrets.yml.example config/secrets.yml
    - cp config/ci.database.yml config/database.yml
    - cp .env.example .env
    - yarn
    - bundle install --path vendor
    - bundle exec rails db:create
    - bundle exec rails db:schema:load
  script:
    - bundle exec rspec

jest:
  image: atomicjolt/atomicjolt-ci:ruby-2.5.7--node-10.18.0--yarn-1.10.1
  only:
    - master
    - /.*\..*/
    - merge_requests
  before_script:
    - cp .env.example .env
    - yarn
  script:
    - yarn test

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
